const JSZip = require('jszip');
const cheerio = require('cheerio');

const LANG_NAMES = {
  en: 'English', de: 'Deutsch', fr: 'Français',
  es: 'Español', pt: 'Português', pl: 'Polski', it: 'Italiano',
};

async function generateZip(article, translations, screenshotItems, newScreenshots) {
  const zip = new JSZip();

  // Build screenshot map: originalSrc → { data, mimeType }
  const screenshotMap = {};
  for (const item of screenshotItems) {
    if (newScreenshots[item.src]) {
      screenshotMap[item.src] = newScreenshots[item.src];
    }
  }

  for (const [lang, translation] of Object.entries(translations)) {
    const langFolder = zip.folder(lang);
    const imgFolder = langFolder.folder('images');

    // Process HTML: replace image srcs
    const $ = cheerio.load(translation.contentHtml, { decodeEntities: false });
    const usedImages = {};

    $('img').each((i, el) => {
      const src = $(el).attr('src') || $(el).attr('data-src');
      if (!src) return;

      if (screenshotMap[src]) {
        // New portal screenshot
        const fileName = `screenshot_${i + 1}.png`;
        usedImages[fileName] = screenshotMap[src];
        $(el).attr('src', `images/${fileName}`);
        $(el).removeAttr('data-src');
      } else {
        // Keep original URL (absolute)
        const item = screenshotItems.find(s => s.src === src);
        if (item) {
          $(el).attr('src', item.absoluteUrl);
        }
      }
    });

    // Add images to zip
    for (const [fileName, imgData] of Object.entries(usedImages)) {
      imgFolder.file(fileName, Buffer.from(imgData.data, 'base64'));
    }

    const processedHtml = $.html();
    const fullHtml = buildHtmlPage(translation.title, processedHtml, lang);
    langFolder.file('index.html', fullHtml);
  }

  // Add a README
  zip.file('README.txt', buildReadme(Object.keys(translations)));

  const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
  return buffer;
}

function buildHtmlPage(title, content, lang) {
  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 960px;
      margin: 0 auto;
      padding: 48px 24px;
      color: #1e293b;
      line-height: 1.75;
      background: #fff;
    }
    h1 { font-size: 30px; font-weight: 700; margin: 0 0 32px; color: #0f172a; line-height: 1.3; }
    h2 { font-size: 22px; font-weight: 600; margin: 40px 0 16px; color: #0f172a; }
    h3 { font-size: 18px; font-weight: 600; margin: 28px 0 12px; color: #1e293b; }
    h4 { font-size: 16px; font-weight: 600; margin: 20px 0 10px; }
    p { margin: 0 0 16px; }
    ul, ol { padding-left: 28px; margin: 0 0 16px; }
    li { margin-bottom: 8px; }
    img {
      max-width: 100%;
      height: auto;
      border-radius: 10px;
      box-shadow: 0 4px 16px rgba(0,0,0,0.12);
      margin: 20px 0;
      display: block;
    }
    code {
      background: #f1f5f9;
      padding: 2px 7px;
      border-radius: 5px;
      font-family: 'SFMono-Regular', Consolas, monospace;
      font-size: 0.9em;
      color: #0f172a;
    }
    pre {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 10px;
      padding: 20px;
      overflow-x: auto;
      margin: 20px 0;
    }
    pre code { background: none; padding: 0; }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th { background: #f8fafc; font-weight: 600; text-align: left; }
    th, td { padding: 10px 14px; border: 1px solid #e2e8f0; }
    tr:nth-child(even) { background: #f8fafc; }
    blockquote {
      border-left: 4px solid #3b82f6;
      margin: 20px 0;
      padding: 12px 20px;
      background: #eff6ff;
      border-radius: 0 8px 8px 0;
      color: #1e40af;
    }
    .note, .tip {
      background: #f0fdf4;
      border-left: 4px solid #22c55e;
      padding: 14px 18px;
      border-radius: 0 8px 8px 0;
      margin: 20px 0;
    }
    .warning {
      background: #fffbeb;
      border-left: 4px solid #f59e0b;
      padding: 14px 18px;
      border-radius: 0 8px 8px 0;
      margin: 20px 0;
    }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  ${content}
</body>
</html>`;
}

function buildReadme(langs) {
  return `Bitrix24 Localized Articles
===========================

Generated by Bitrix24 Localizer

Languages included:
${langs.map(l => `  - ${l}/ → ${LANG_NAMES[l] || l} (index.html)`).join('\n')}

Each language folder contains:
  - index.html   : The translated article
  - images/      : New screenshots from your Western portal

To view: open index.html in any web browser.
`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

module.exports = { generateZip };
